<?php

/**
 * MIT License
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace SprykerEco\Shared\Payolution;

interface PayolutionConstants
{
    const TRANSACTION_GATEWAY_URL = 'PAYOLUTION:TRANSACTION_GATEWAY_URL';
    const CALCULATION_GATEWAY_URL = 'PAYOLUTION:CALCULATION_GATEWAY_URL';

    const TRANSACTION_SECURITY_SENDER = 'PAYOLUTION:TRANSACTION_SECURITY_SENDER';
    const TRANSACTION_USER_LOGIN = 'PAYOLUTION:TRANSACTION_USER_LOGIN';
    const TRANSACTION_USER_PASSWORD = 'PAYOLUTION:TRANSACTION_USER_PASSWORD';
    const CALCULATION_SENDER = 'PAYOLUTION:CALCULATION_SENDER';
    const CALCULATION_USER_LOGIN = 'PAYOLUTION:CALCULATION_USER_LOGIN';
    const CALCULATION_USER_PASSWORD = 'PAYOLUTION:CALCULATION_USER_PASSWORD';

    const TRANSACTION_MODE = 'PAYOLUTION:TRANSACTION_MODE';
    const CALCULATION_MODE = 'PAYOLUTION:CALCULATION_MODE';

    const TRANSACTION_CHANNEL_INVOICE = 'PAYOLUTION:TRANSACTION_CHANNEL_INVOICE';
    const TRANSACTION_CHANNEL_INSTALLMENT = 'PAYOLUTION:TRANSACTION_CHANNEL_INSTALLMENT';
    const TRANSACTION_CHANNEL_PRE_CHECK = 'PAYOLUTION:TRANSACTION_CHANNEL_PRE_CHECK';
    const CALCULATION_CHANNEL = 'PAYOLUTION:CALCULATION_CHANNEL';

    const MIN_ORDER_GRAND_TOTAL_INVOICE = 'PAYOLUTION:MIN_ORDER_GRAND_TOTAL_INVOICE';
    const MAX_ORDER_GRAND_TOTAL_INVOICE = 'PAYOLUTION:MAX_ORDER_GRAND_TOTAL_INVOICE';
    const MIN_ORDER_GRAND_TOTAL_INSTALLMENT = 'PAYOLUTION:MIN_ORDER_GRAND_TOTAL_INSTALLMENT';
    const MAX_ORDER_GRAND_TOTAL_INSTALLMENT = 'PAYOLUTION:MAX_ORDER_GRAND_TOTAL_INSTALLMENT';

    const PAYOLUTION_BCC_EMAIL_ADDRESS = 'PAYOLUTION:PAYOLUTION_BCC_EMAIL_ADDRESS';
    const EMAIL_TEMPLATE_NAME = 'PAYOLUTION:EMAIL_TEMPLATE_NAME';
    const EMAIL_FROM_NAME = 'PAYOLUTION:EMAIL_FROM_NAME';
    const EMAIL_FROM_ADDRESS = 'PAYOLUTION:EMAIL_FROM_ADDRESS';
    const EMAIL_SUBJECT = 'PAYOLUTION:EMAIL_SUBJECT';
}
