<?php

/**
 * MIT License
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace SprykerEco\Shared\Payolution;

/**
 * Declares global environment configuration keys. Do not use it for other class constants.
 */
interface PayolutionConstants
{
    public const TRANSACTION_GATEWAY_URL = 'PAYOLUTION:TRANSACTION_GATEWAY_URL';
    public const CALCULATION_GATEWAY_URL = 'PAYOLUTION:CALCULATION_GATEWAY_URL';

    public const TRANSACTION_SECURITY_SENDER = 'PAYOLUTION:TRANSACTION_SECURITY_SENDER';
    public const TRANSACTION_USER_LOGIN = 'PAYOLUTION:TRANSACTION_USER_LOGIN';
    public const TRANSACTION_USER_PASSWORD = 'PAYOLUTION:TRANSACTION_USER_PASSWORD';
    public const CALCULATION_SENDER = 'PAYOLUTION:CALCULATION_SENDER';
    public const CALCULATION_USER_LOGIN = 'PAYOLUTION:CALCULATION_USER_LOGIN';
    public const CALCULATION_USER_PASSWORD = 'PAYOLUTION:CALCULATION_USER_PASSWORD';

    public const TRANSACTION_MODE = 'PAYOLUTION:TRANSACTION_MODE';
    public const CALCULATION_MODE = 'PAYOLUTION:CALCULATION_MODE';

    public const TRANSACTION_CHANNEL_INVOICE = 'PAYOLUTION:TRANSACTION_CHANNEL_INVOICE';
    public const TRANSACTION_CHANNEL_INSTALLMENT = 'PAYOLUTION:TRANSACTION_CHANNEL_INSTALLMENT';
    public const TRANSACTION_CHANNEL_PRE_CHECK = 'PAYOLUTION:TRANSACTION_CHANNEL_PRE_CHECK';
    public const CALCULATION_CHANNEL = 'PAYOLUTION:CALCULATION_CHANNEL';

    public const MIN_ORDER_GRAND_TOTAL_INVOICE = 'PAYOLUTION:MIN_ORDER_GRAND_TOTAL_INVOICE';
    public const MAX_ORDER_GRAND_TOTAL_INVOICE = 'PAYOLUTION:MAX_ORDER_GRAND_TOTAL_INVOICE';
    public const MIN_ORDER_GRAND_TOTAL_INSTALLMENT = 'PAYOLUTION:MIN_ORDER_GRAND_TOTAL_INSTALLMENT';
    public const MAX_ORDER_GRAND_TOTAL_INSTALLMENT = 'PAYOLUTION:MAX_ORDER_GRAND_TOTAL_INSTALLMENT';

    public const PAYOLUTION_BCC_EMAIL_ADDRESS = 'PAYOLUTION:PAYOLUTION_BCC_EMAIL_ADDRESS';
    public const EMAIL_TEMPLATE_NAME = 'PAYOLUTION:EMAIL_TEMPLATE_NAME';
    public const EMAIL_FROM_NAME = 'PAYOLUTION:EMAIL_FROM_NAME';
    public const EMAIL_FROM_ADDRESS = 'PAYOLUTION:EMAIL_FROM_ADDRESS';
    public const EMAIL_SUBJECT = 'PAYOLUTION:EMAIL_SUBJECT';
}
